### ISSUE TITLE
Maintaining references to original layer

### ISSUE THREAD

**Issue by alexcroox** [makinacorpus/Leaflet.AlmostOver#4]
I set a custom object property on the layer before adding it to the almostOver layer group. When `almost:click` is triggered that property is no longer present.

```
map.cableLayer = new L.featureGroup();

L.geoJson(data, {
    onEachFeature: function(feature, layer) {

        // layer.cableId set in the layer
        layer.cableId = layer.feature.properties.cable_id;

        map.cableLayer.addLayer(layer);

        layer.on('click', function(e) {

            sidebar.focusCable(e.target, e.latlng);
        });
    }
});

map.m.almostOver.addLayer(map.cableLayer);
map.cableLayer.addTo(map.m);

 map.m.on('almost:click', function(e) {

    console.log(e); // layer.cableId not present in e.layer or e.target
    sidebar.focusCable(e.target, e.latlng);
});
```

**Comment by alexcroox** [comment]
These are GeometryCollections if that helps (each layer is a set of LineStrings)

**Comment by leplatrem** [comment]
Yes, indeed : the layer where you set the attribute is the collection, whereas the layer that is received in the event is the sub-linestring.

This is due to this piece of code : https://github.com/makinacorpus/Leaflet.AlmostOver/blob/gh-pages/leaflet.almostover.js#L59-L62 which adds recursively group layers.

If you like to contribute an option to the addLayer function that would disable this or keep a reference on the parent, please open a pull request, we'll review it and merge it !

Thanks!

**Comment by alexcroox** [comment]
Would there be anyway to duplicate the data on all polylines in that single layer?

**Comment by leplatrem** [comment]
Well you could simply do that:

``` javascript
L.geoJson(data, {
    onEachFeature: function(feature, layer) {
        layer.cableId = feature.properties.cable_id;
        // layer is a geometrycollection
        layer.eachLayer(function (l) {
           l.cableId = feature.properties.cable_id;
        });
    }
```

**Comment by alexcroox** [comment]
This works great thank you! I never thought to do a further `eachlayer()`...

A slight amendment to handle those that aren't collections otherwise it breaks execution:

```
if(typeof layer.eachLayer == 'function')
    layer.eachLayer(function (l) {
        l.cableId = feature.properties.cable_id;
    });
```
